11 
    de.renew.gui.CPNDrawing 3 
        de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1 257 67 24 16 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 3 2 269 83 269 112 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 1  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 4 259 111 20 20 NULL    REF 6 NULL  964 396 614 600 